export const SET_MOBILE= 'SET_MOBILE';
export const REGISTER_REQUEST= 'REGISTER_REQUEST';
export const REGISTER_SUCCESS= 'REGISTER_SUCCESS';
export const REGISTER_FAILURE= 'REGISTER_FAILURE';

export const REQUEST_OTP='REQUEST_OTP';
export const REQUEST_OTP_SUCCESS='REQUEST_OTP_SUCCESS';
export const REQUEST_OTP_FAILURE='REQUEST_OTP_FAILURE';


export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const SET_USER_INFO= 'SET_USER_INFO';

